version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        port:
            - "3000:3000"
        volumes:
            - /home/node/app/node_modules
            - .:/home/node/app